#!/usr/bin/env python

import os
#import json
#import sys
#from time import sleep
import digitalocean

do_token = os.environ.get("DO_TOKEN")
if not do_token: do_token = os.environ["DIGITALOCEAN_TOKEN"]

manager = digitalocean.Manager(token=do_token)
print(manager.get_all_droplets())

# Creating a Droplet and checking its status
name = os.environ["NAME"]
region = os.environ.get("DO_DEFAULT_REGION","nyc3")
image = os.environ.get("IMAGE","53263886")
size = os.environ.get("DROPLET_SIZE","s-1vcpu-1gb")
backup = os.environ.get("BACKUP")
private_networking = os.environ.get("PRIVATE_NETWORKING",True)
monitoring = os.environ.get("MONITORING",True)
key_id = os.environ.get("KEY_ID")


inputargs = { "token":do_token,
              "name":name,
              "region":region,
              "image":image,
              "size_slug":size }

if backup: inputargs["backups"] = True
if monitoring: inputargs["monitoring"] = True
if key_id: inputargs["ssh_keys"] = key_id

droplet = digitalocean.Droplet(**inputargs)
droplet.create()

actions = droplet.get_actions()

for action in actions:
    action.load()
    # Once it shows complete, droplet is up and running
    print action.status
